"""baseline control plane

Revision ID: 5d214539fbc4
Revises: 
Create Date: 2026-08-17 21:30:08.567528
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '5d214539fbc4'
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('actor_label', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('before', sa.JSON(), nullable=False),
    sa.Column('after', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('billing_model', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_per_seat', sa.Float(), nullable=False),
    sa.Column('price_flat', sa.Float(), nullable=False),
    sa.Column('attempt_allowance', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uq_plan_code_version')
    )
    op.create_index(op.f('ix_plans_code'), 'plans', ['code'], unique=False)
    op.create_table('platform_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_users_email'), 'platform_users', ['email'], unique=True)
    op.create_table('provider_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('capability', sa.String(length=40), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('provider_version', sa.String(length=30), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=False),
    sa.Column('used_fallback', sa.Boolean(), nullable=False),
    sa.Column('cost_paise', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_calls_at'), 'provider_calls', ['at'], unique=False)
    op.create_index(op.f('ix_provider_calls_capability'), 'provider_calls', ['capability'], unique=False)
    op.create_index(op.f('ix_provider_calls_provider_id'), 'provider_calls', ['provider_id'], unique=False)
    op.create_index(op.f('ix_provider_calls_tenant_id'), 'provider_calls', ['tenant_id'], unique=False)
    op.create_table('provider_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('capability', sa.String(length=40), nullable=False),
    sa.Column('provider_key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('entrypoint', sa.String(length=200), nullable=False),
    sa.Column('config_schema', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capability', 'provider_key', 'version', name='uq_provider_capability_key_version')
    )
    op.create_index(op.f('ix_provider_registry_capability'), 'provider_registry', ['capability'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('eval_metrics', sa.JSON(), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_provider_id'), 'model_versions', ['provider_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('seat_limit', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=60), nullable=False),
    sa.Column('branding', sa.JSON(), nullable=False),
    sa.Column('season_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('season_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('feature_flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'tenant_id', name='uq_flag_key_scope')
    )
    op.create_index(op.f('ix_feature_flags_key'), 'feature_flags', ['key'], unique=False)
    op.create_table('gamification_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('xp_table', sa.JSON(), nullable=False),
    sa.Column('difficulty_multipliers', sa.JSON(), nullable=False),
    sa.Column('weakness_multiplier', sa.Float(), nullable=False),
    sa.Column('streak_rules', sa.JSON(), nullable=False),
    sa.Column('free_freezes_per_month', sa.Integer(), nullable=False),
    sa.Column('quiz_xp_cap_percent', sa.Integer(), nullable=False),
    sa.Column('leagues_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_engagement_notifications_per_day', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('gst_rate', sa.Float(), nullable=False),
    sa.Column('gst_amount', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_table('provider_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('capability', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('primary_provider_id', sa.String(length=36), nullable=False),
    sa.Column('fallback_provider_id', sa.String(length=36), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('shadow_provider_id', sa.String(length=36), nullable=True),
    sa.Column('canary_percent', sa.Integer(), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fallback_provider_id'], ['provider_registry.id'], ),
    sa.ForeignKeyConstraint(['primary_provider_id'], ['provider_registry.id'], ),
    sa.ForeignKeyConstraint(['shadow_provider_id'], ['provider_registry.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capability', 'tenant_id', name='uq_provider_config_scope')
    )
    op.create_index(op.f('ix_provider_configs_capability'), 'provider_configs', ['capability'], unique=False)
    op.create_index(op.f('ix_provider_configs_tenant_id'), 'provider_configs', ['tenant_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('negotiated_price', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('renews_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_table('tenant_user_directory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_slug', sa.String(length=60), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_user_directory_email'), 'tenant_user_directory', ['email'], unique=True)
    op.create_index(op.f('ix_tenant_user_directory_tenant_id'), 'tenant_user_directory', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_user_directory_tenant_slug'), 'tenant_user_directory', ['tenant_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_user_directory_tenant_slug'), table_name='tenant_user_directory')
    op.drop_index(op.f('ix_tenant_user_directory_tenant_id'), table_name='tenant_user_directory')
    op.drop_index(op.f('ix_tenant_user_directory_email'), table_name='tenant_user_directory')
    op.drop_table('tenant_user_directory')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_provider_configs_tenant_id'), table_name='provider_configs')
    op.drop_index(op.f('ix_provider_configs_capability'), table_name='provider_configs')
    op.drop_table('provider_configs')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('gamification_configs')
    op.drop_index(op.f('ix_feature_flags_key'), table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_model_versions_provider_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_provider_registry_capability'), table_name='provider_registry')
    op.drop_table('provider_registry')
    op.drop_index(op.f('ix_provider_calls_tenant_id'), table_name='provider_calls')
    op.drop_index(op.f('ix_provider_calls_provider_id'), table_name='provider_calls')
    op.drop_index(op.f('ix_provider_calls_capability'), table_name='provider_calls')
    op.drop_index(op.f('ix_provider_calls_at'), table_name='provider_calls')
    op.drop_table('provider_calls')
    op.drop_index(op.f('ix_platform_users_email'), table_name='platform_users')
    op.drop_table('platform_users')
    op.drop_index(op.f('ix_plans_code'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
